on:
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:
    branches:
      - 'master'
      - 'develop'
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check build success step
        uses: ./.github/actions/check-build
        id: is_build_success
      - name: Check unit tests success step
        uses: ./.github/actions/run-unit-test
        id: is_unit_tests_result
